# Generated by Django 2.0.3 on 2018-05-10 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180510_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcompetency',
            name='who_verified',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenteducation',
            name='degree',
            field=models.CharField(choices=[('bac', 'Бакалавриат'), ('mag', 'Магистратура')], default=None, max_length=3),
        ),
    ]
