# Generated by Django 2.0.3 on 2018-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180511_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteducation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
