# Generated by Django 2.0.3 on 2018-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentjob_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='bg_src',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='icon_src',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
