# Generated by Django 2.0.3 on 2018-05-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180513_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAreaVacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='university',
            name='bg_src',
            field=models.CharField(blank=True, default='http://2bddea4c.ngrok.io/static/img/no-image.jpg', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='icon_src',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='subject_area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SubjectAreaVacancies'),
        ),
    ]
